---
- name: deploy
  hosts: web
  serial: 1

  tasks:
      - name: disable webnode
        debug:
            msg: "disable {{ inventory_hostname }}"
        delegate_to: "{{ groups['lb'][0] }}"

      - name: upgrade web
        debug:
            msg: "upgrade software"

      - name: enable node
        debug:
            msg: "enable {{ inventory_hostname }}"
        delegate_to: "{{ groups['lb'][0] }}"
